// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiUypPyJHfcfjQSZGO28_9q7N89D5SqMw',
    appId: '1:304627475188:web:bc11c80997d34b3d9cf4a1',
    messagingSenderId: '304627475188',
    projectId: 'augen-eb7a1',
    authDomain: 'augen-eb7a1.firebaseapp.com',
    storageBucket: 'augen-eb7a1.appspot.com',
    measurementId: 'G-S8RLFX7ED2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvLMqE1VIojNQFxGa8fHIvuKmW-WBRCA',
    appId: '1:304627475188:android:e5364540e6cf3b0c9cf4a1',
    messagingSenderId: '304627475188',
    projectId: 'augen-eb7a1',
    storageBucket: 'augen-eb7a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOWu5j_qSDeFJDeezSsu60RPQF_T_7Mw4',
    appId: '1:304627475188:ios:3460a445ba1151319cf4a1',
    messagingSenderId: '304627475188',
    projectId: 'augen-eb7a1',
    storageBucket: 'augen-eb7a1.appspot.com',
    androidClientId: '304627475188-e7vmpl8heipbqertqc4km3rc1rc8fkm7.apps.googleusercontent.com',
    iosClientId: '304627475188-s5sjkmsgtq1umtqlg041bekr7dben1r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.otp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOWu5j_qSDeFJDeezSsu60RPQF_T_7Mw4',
    appId: '1:304627475188:ios:3460a445ba1151319cf4a1',
    messagingSenderId: '304627475188',
    projectId: 'augen-eb7a1',
    storageBucket: 'augen-eb7a1.appspot.com',
    androidClientId: '304627475188-e7vmpl8heipbqertqc4km3rc1rc8fkm7.apps.googleusercontent.com',
    iosClientId: '304627475188-s5sjkmsgtq1umtqlg041bekr7dben1r7.apps.googleusercontent.com',
    iosBundleId: 'com.example.otp',
  );
}
